---
- name: Ansible block module examples
  hosts: localhost

  tasks:
  - block:
    - name: Install httpd on Redhat family
      yum:
        name: httpd
        state: present
      when: ansible_os_family =='RedHat'

    - name: copy the jinja template
      template:
        src: hostdetails.txt.j2
        dest: /home/devops/hostdetails.txt
      when: ansible_os_family =='RedHat'

    - name: start the httpd service on Redhat family
      service:
        name: httpd
        state: started
      when: ansible_os_family =='RedHat'
      become: yes

  - block:
    - name: Install apache2 on Debian family
      yum:
        name: apache2
        state: present
      when: ansible_os_family =='RedHat'
        
    - name: copy the jinja template
      template:
        src: hostdetails.txt.j2
        dest: /home/devops/hostdetails.txt

    - name: start the apache2 service on Debian family
      service:
        name: apache2
        state: started
      when: ansible_os_family =='Debian'
      become: yes

    - debug:
        msg: "playbook execution completed"
...