---
- name: Error handling
  hosts: localhost

  tasks:
   - block:
      - name: Install apache1
        apt:
         name: apache1
         state: present
     rescue:
      - name: Install apache2
        apt:
         name: apache2
         state: present
     always:
      - name: Check url response
        uri:
         url: "{{item}}"
        with_items:
         - http://localhost
         - http://172.18.0.1
         - http://172.18.0.2
...