---
- hosts: localhost
  become: true
  vars:
    name: KUMAR
      
  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present

  - name: Copy index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
    notify:
    - Restart apache2
      
  handlers:
  - name: Restart apache2
    service:
      name: apache2
      state: restarted
...