---
- hosts: localhost
  become: true
 
  tasks:
  - name: Copy files
    ignore_errors: yes
    copy:  
      src: "{{item.source}}"
      dest: "{{item.destination}}"
      mode: "{{item.mode}}"
    with_items: 
    - {"source": "text.xml","destination": "/tmp/", "mode": "0700"}
    - {"source": "abc.xml","destination": "/opt/", "mode": "0777"}
...