---
- name: Ansible import/include module examples
  hosts: localhost
  become: yes

  tasks:
  - import_tasks: install_pkgs_RedHat.yml
    when: ansible_os_family =='RedHat'

  - import_tasks: install_pkgs_Debian.yml
    when: ansible_os_family =='Debian'
...