---
# handlers file for apache2
- name: restart apache2
  service: 
    name: apache2
    state: restarted
  when: ansible_os_family =='Debian'

- name: restart httpd
  service:
    name: httpd
    state: restarted
  when: ansible_os_family =='RedHat'